"""empty message

Revision ID: 280055fcc3e6
Revises: 7ea2928de1a2
Create Date: 2024-07-12 11:10:55.393336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280055fcc3e6'
down_revision = '7ea2928de1a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
